### ISSUE TITLE
Materialgram seems to be flagged as trojan and miner by windows defender and virustotal

### ISSUE THREAD

**Issue by hackmonker** [kukuruzka165/materialgram#26]
### Steps to reproduce

1. Turn on Windows defender
2. Let it scan materialgram
3. get quarentined

### Expected behaviour

Not get quarantined and not getting flagged

### Actual behaviour

Gets flagged by virustotal and Windows defender

![image](https://github.com/kukuruzka165/materialgram/assets/46002790/6b4f5bc9-696e-465c-b8ed-e42fe0ae413a)
![image](https://github.com/kukuruzka165/materialgram/assets/46002790/58aa4f35-b37d-460f-b18e-5a033c5ca4ab)

### Operating system

Windows 11

### Version of Telegram Desktop

5.1.5.1

### Installation source

Static binary from official website

It might be a false positive but any reason why it is being flagged in the first place?

**Comment by kukuruzka165** [comment]
This can happen with any telegram fork because it is a popular software without an official signature.
I just downloaded the latest version of telegram from the official website:

![chrome_JMT1wFStcw](https://github.com/kukuruzka165/materialgram/assets/60149954/99ee9417-a24d-4613-a1d8-5603f98a62fe)

and now let's change 1 random bit inside the .exe file to make the telegram signature no longer valid

![image](https://github.com/kukuruzka165/materialgram/assets/60149954/56221ceb-d399-467d-b6cf-908b7c1c572b)

and we get one more false positive
i still don't understand why Windows Defender sees materialgram as a virus for some people because it never happed to me

![image](https://github.com/kukuruzka165/materialgram/assets/60149954/f2ab8b87-c7bc-4c24-8b1b-eed0a1066e41)

in any case, you can build yourself or just stop using materialgram at all

**Comment by hackmonker** [comment]
Thanks for the clarification. I suspected it was a false positive since I have been using it for some time now but just wanted to get a clarification for the unnecessary flagging of defender and virustotal.

**Comment by pfcdx** [comment]
> in any case, you can build yourself or just stop using materialgram at all

Well, building the same thing won't change something.

@kukuruzka165, you have to report that materialgram is safe, and their detection is a false-positive to Microsoft: https://learn.microsoft.com/en-us/defender-office-365/air-report-false-positives-negatives 

And to answer the flag, all of them is ML or Heur tagged, which means they are automated detections by some set of rules.
Mostly, they are false-positive detections. And I can say that materialgram is safe in that matter.

If you don't feel safe, fork the repo; build it in Actions, audit over the commits if you are that paranoid.
